### ISSUE TITLE
Trigger timings of DIV&CON

### ISSUE THREAD

**Issue by colus-img** [mhetrick/nonlinearcircuits#5]
Thanks for the interesting module.
I tried to use, but the trigger timings are not aligned.
When I look at the SCOPE, the timing of the trigger opening is not aligned. On the other hand, the closing timing is aligned.
I think this is difficult to use, is this a specification?

![211017](https://user-images.githubusercontent.com/5661132/137619833-0da4ab95-4fbd-4c50-8723-5d359becf7d9.jpg)

**Comment by mhetrick** [comment]
I just now saw this report, sorry! It's fixed in 2.0.1. Sending to the library now.
